name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker://barksim/bark-ml:latest
    steps:
      - uses: actions/checkout@v1
      - name: Setting up virtual environment
        run: virtualenv -p python3 ./bark_ml/python_wrapper/venv  --system-site-packages
      - name: Entering the virtual python environment..
        run: . ./bark_ml/python_wrapper/venv/bin/activate
      - name: Installing additional Python packages..
        run: pip install tf2_gnn spektral tensorflow-addons==0.11.2 graph-nets==1.1.0
      - name: Running unit tests..
        run: bazel test :unit_tests
      - name: Running graph tests..
        run: bazel test :graph_tests
      - name: Running examples..
        run: bazel test :examples_tests
